articulos/urls.py
from django.urls import path
from articulos import views

urlpatterns=[
    path(
        route='',
        view=views.listar_articulos,
        name='index'
    ),
    path(
        route='create/',
        view=views.create_articulo,
        name='create'
    ),
    path(
        route='update/<int:id>/',
        view=views.update_articulo,
        name='update'
    ),
    path(
        route='delete/<int:id>/',
        view=views.delete_articulo,
        name='delete'
    ),
]

crudbasico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include(('articulos.urls', 'articulos'), namespace='articulos'))
]

articulos/models.py
from django.db import models

class Marca(models.Model):
    descripcion=models.CharField(max_length=100)

    created=models.DateTimeField(auto_now_add=True)
    modified=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.descripcion
        
class Articulo(models.Model):
    marca=models.ForeignKey(Marca, on_delete=models.CASCADE)
    codigo=models.CharField(max_length=10)
    descripcion=models.CharField(max_length=100)
    cantidad=models.IntegerField()
    precio=models.DecimalField(max_digits=8,decimal_places=2)

    created=models.DateTimeField(auto_now_add=True)
    modified=models.DateTimeField(auto_now=True)


articulos/forms.py
from django import forms
from django.forms import fields
from .models import *

class ArticuloForm(forms.ModelForm):
    class Meta:
        model=Articulo
        fields=('codigo', 'marca', 'descripcion', 'cantidad', 'precio')

articulos/views.py
from django.shortcuts import render, redirect
from articulos.forms import ArticuloForm
from articulos.models import Articulo

def listar_articulos(request):
    articulos=Articulo.objects.all().order_by('-created')
    return render(request, 'articulos/index.html',{'articulos':articulos})
    

def create_articulo(request):
    if request.method=='POST':
        form=ArticuloForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('articulos:index')
    else:
        form=ArticuloForm()
    return render(request, 'articulos/create_update.html', {'form':form, 'dato':True})

def update_articulo(request, id):
    articulo=Articulo.objects.get(id=id)
    if request.method=='GET':
        form=ArticuloForm(instance=articulo)
    else:
        form=ArticuloForm(request.POST, instance=articulo)
        if form.is_valid():
            form.save()
            return redirect('articulos:index')
    return render(request, 'articulos/create_update.html', {'form':form, 'dato':False})

def delete_articulo(request, id):
    articulo=Articulo.objects.get(id=id)
    descripcion=articulo.descripcion
    if request.method=='POST':
        articulo.delete()
        return redirect('articulos:index')
    return render(request, 'articulos/delete.html', {'descripcion':descripcion})
        
            
        

# Create your views here.

templates/articulos/create_update.html
{% extends 'base.html' %}
{% block content %}
{% if dato %}
<h2>Crear registro</h2>
{% else %}
<h2>Editar registro</h2>
{% endif %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
    <a href="{% url 'articulos:index' %}" class="btn btn-danger">Cancelar</a>
</form>
{% endblock %}

templates/articulos/delete.html
{% extends 'base.html' %}
{% block content %}
<h2>Eliminar registro</h2>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Esta seguro que desea eliminar el registro <span>{{descripcion}}</span></h3>
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Eliminar</button>
    <a href="{% url 'articulos:index' %}" class="btn btn-danger">Cancelar</a>
    </div>
    
</form>
{% endblock %}

templates/articulos/index.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'articulos:create' %}" class="btn btn-primary">CREAR</a>
<table class="table table-dark table-striped mt-3">
    <thead>
        <tr class="text-center">
            <th scope="col">ID</th>
            <th scope="col">CODIGO</th>
            <th scope="col">MARCA</th>
            <th scope="col">DESCRIPCION</th>
            <th scope="col">CANTIDAD</th>
            <th scope="col">PRECIO</th>
            <th scope="col" >ACCION</th>
        </tr>
    </thead>
    <tbody>
        {% for articulo in articulos %}
        <tr class="text-center">
            <td>{{articulo.id}}</td>
            <td>{{articulo.codigo}}</td>
            <td>{{articulo.marca}}</td>
            <td>{{articulo.descripcion}}</td>
            <td>{{articulo.cantidad}}</td>
            <td>{{articulo.precio}}</td>
            <td>
                <a href="{% url 'articulos:update' articulo.id %}" class="btn btn-primary">Editar</a>
                <a href="{% url 'articulos:delete' articulo.id  %}" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>CRUD</title>
</head>
<body>
    <h1 class="text-center">CRUD CON DJANGO</h1>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>